/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated.review'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated.disputes'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated.availability'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated.tasks.index'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated.tasks.new'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated.tasks.$taskId'
import { Route as AuthenticatedDashboardTeamLeadRouteImport } from './routes/_authenticated.dashboard.team-lead'
import { Route as AuthenticatedDashboardManagementRouteImport } from './routes/_authenticated.dashboard.management'
import { Route as AuthenticatedDashboardFinancialRouteImport } from './routes/_authenticated.dashboard.financial'
import { Route as AuthenticatedDashboardEmployeeRouteImport } from './routes/_authenticated.dashboard.employee'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated.admin.roles'
import { Route as AuthenticatedAdminRejectionCategoriesRouteImport } from './routes/_authenticated.admin.rejection-categories'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated.admin.projects'
import { Route as AuthenticatedAdminPlatformsRouteImport } from './routes/_authenticated.admin.platforms'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTeamLeadRoute =
  AuthenticatedDashboardTeamLeadRouteImport.update({
    id: '/dashboard/team-lead',
    path: '/dashboard/team-lead',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardManagementRoute =
  AuthenticatedDashboardManagementRouteImport.update({
    id: '/dashboard/management',
    path: '/dashboard/management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFinancialRoute =
  AuthenticatedDashboardFinancialRouteImport.update({
    id: '/dashboard/financial',
    path: '/dashboard/financial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardEmployeeRoute =
  AuthenticatedDashboardEmployeeRouteImport.update({
    id: '/dashboard/employee',
    path: '/dashboard/employee',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRejectionCategoriesRoute =
  AuthenticatedAdminRejectionCategoriesRouteImport.update({
    id: '/admin/rejection-categories',
    path: '/admin/rejection-categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/admin/projects',
    path: '/admin/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPlatformsRoute =
  AuthenticatedAdminPlatformsRouteImport.update({
    id: '/admin/platforms',
    path: '/admin/platforms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/rejection-categories': typeof AuthenticatedAdminRejectionCategoriesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/employee': typeof AuthenticatedDashboardEmployeeRoute
  '/dashboard/financial': typeof AuthenticatedDashboardFinancialRoute
  '/dashboard/management': typeof AuthenticatedDashboardManagementRoute
  '/dashboard/team-lead': typeof AuthenticatedDashboardTeamLeadRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/rejection-categories': typeof AuthenticatedAdminRejectionCategoriesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/employee': typeof AuthenticatedDashboardEmployeeRoute
  '/dashboard/financial': typeof AuthenticatedDashboardFinancialRoute
  '/dashboard/management': typeof AuthenticatedDashboardManagementRoute
  '/dashboard/team-lead': typeof AuthenticatedDashboardTeamLeadRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/disputes': typeof AuthenticatedDisputesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/rejection-categories': typeof AuthenticatedAdminRejectionCategoriesRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dashboard/employee': typeof AuthenticatedDashboardEmployeeRoute
  '/_authenticated/dashboard/financial': typeof AuthenticatedDashboardFinancialRoute
  '/_authenticated/dashboard/management': typeof AuthenticatedDashboardManagementRoute
  '/_authenticated/dashboard/team-lead': typeof AuthenticatedDashboardTeamLeadRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/availability'
    | '/disputes'
    | '/profile'
    | '/review'
    | '/auth/callback'
    | '/admin/platforms'
    | '/admin/projects'
    | '/admin/rejection-categories'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/employee'
    | '/dashboard/financial'
    | '/dashboard/management'
    | '/dashboard/team-lead'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/availability'
    | '/disputes'
    | '/profile'
    | '/review'
    | '/auth/callback'
    | '/admin/platforms'
    | '/admin/projects'
    | '/admin/rejection-categories'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/employee'
    | '/dashboard/financial'
    | '/dashboard/management'
    | '/dashboard/team-lead'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forbidden'
    | '/login'
    | '/_authenticated/availability'
    | '/_authenticated/disputes'
    | '/_authenticated/profile'
    | '/_authenticated/review'
    | '/auth/callback'
    | '/_authenticated/admin/platforms'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/rejection-categories'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/dashboard/employee'
    | '/_authenticated/dashboard/financial'
    | '/_authenticated/dashboard/management'
    | '/_authenticated/dashboard/team-lead'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/new'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/team-lead': {
      id: '/_authenticated/dashboard/team-lead'
      path: '/dashboard/team-lead'
      fullPath: '/dashboard/team-lead'
      preLoaderRoute: typeof AuthenticatedDashboardTeamLeadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/management': {
      id: '/_authenticated/dashboard/management'
      path: '/dashboard/management'
      fullPath: '/dashboard/management'
      preLoaderRoute: typeof AuthenticatedDashboardManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/financial': {
      id: '/_authenticated/dashboard/financial'
      path: '/dashboard/financial'
      fullPath: '/dashboard/financial'
      preLoaderRoute: typeof AuthenticatedDashboardFinancialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/employee': {
      id: '/_authenticated/dashboard/employee'
      path: '/dashboard/employee'
      fullPath: '/dashboard/employee'
      preLoaderRoute: typeof AuthenticatedDashboardEmployeeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rejection-categories': {
      id: '/_authenticated/admin/rejection-categories'
      path: '/admin/rejection-categories'
      fullPath: '/admin/rejection-categories'
      preLoaderRoute: typeof AuthenticatedAdminRejectionCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/platforms': {
      id: '/_authenticated/admin/platforms'
      path: '/admin/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AuthenticatedAdminPlatformsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedAdminPlatformsRoute: typeof AuthenticatedAdminPlatformsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminRejectionCategoriesRoute: typeof AuthenticatedAdminRejectionCategoriesRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedDashboardEmployeeRoute: typeof AuthenticatedDashboardEmployeeRoute
  AuthenticatedDashboardFinancialRoute: typeof AuthenticatedDashboardFinancialRoute
  AuthenticatedDashboardManagementRoute: typeof AuthenticatedDashboardManagementRoute
  AuthenticatedDashboardTeamLeadRoute: typeof AuthenticatedDashboardTeamLeadRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedAdminPlatformsRoute: AuthenticatedAdminPlatformsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminRejectionCategoriesRoute:
    AuthenticatedAdminRejectionCategoriesRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDashboardEmployeeRoute: AuthenticatedDashboardEmployeeRoute,
  AuthenticatedDashboardFinancialRoute: AuthenticatedDashboardFinancialRoute,
  AuthenticatedDashboardManagementRoute: AuthenticatedDashboardManagementRoute,
  AuthenticatedDashboardTeamLeadRoute: AuthenticatedDashboardTeamLeadRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
