"""operations and disputes models

Revision ID: c5d888e9fd6a
Revises: b9bfadafa8b5
Create Date: 2026-06-04 10:24:26.963904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c5d888e9fd6a"
down_revision: Union[str, Sequence[str], None] = "b9bfadafa8b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rejection_categories",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rejection_categories")),
    )
    op.create_table(
        "availability_logs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'absent', 'blocked')", name="ck_availability_status"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_availability_logs_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_logs")),
        sa.UniqueConstraint("user_id", "log_date", name="uq_availability_per_day"),
    )
    op.create_table(
        "tasks",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_type_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column("external_task_id", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("time_spent_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rate_id", sa.Uuid(), nullable=True),
        sa.Column("rate_snapshot", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("platform_submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected', 'escalated')",
            name="ck_tasks_status",
        ),
        sa.CheckConstraint("rate_snapshot >= 0", name="ck_tasks_snapshot_nonneg"),
        sa.CheckConstraint("time_spent_hours >= 0", name="ck_tasks_hours_nonneg"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tasks_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rate_id"],
            ["project_rates.id"],
            name=op.f("fk_tasks_rate_id_project_rates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_tasks_reviewed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_tasks_submitted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"],
            ["task_types.id"],
            name=op.f("fk_tasks_task_type_id_task_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint(
            "project_id", "external_task_id", name="uq_external_task_per_project"
        ),
    )
    op.create_table(
        "rejections",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column(
            "rejected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["rejection_categories.id"],
            name=op.f("fk_rejections_category_id_rejection_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_rejections_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rejections")),
        sa.UniqueConstraint("task_id", name="uq_one_rejection_per_task"),
    )
    op.create_table(
        "task_attachments",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=150), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_url", sa.String(length=1000), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("file_size_bytes >= 0", name="ck_attachment_size_nonneg"),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_attachments_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_task_attachments_uploaded_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_attachments")),
    )
    op.create_table(
        "counter_arguments",
        sa.Column("rejection_id", sa.Uuid(), nullable=False),
        sa.Column("argument", sa.Text(), nullable=False),
        sa.Column(
            "lead_decision",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "lead_decision IN ('pending', 'rejected', 'escalated')",
            name="ck_counter_lead_decision",
        ),
        sa.ForeignKeyConstraint(
            ["rejection_id"],
            ["rejections.id"],
            name=op.f("fk_counter_arguments_rejection_id_rejections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_counter_arguments_reviewed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_counter_arguments")),
        sa.UniqueConstraint("rejection_id", name="uq_one_counter_per_rejection"),
    )
    op.create_table(
        "platform_disputes",
        sa.Column("counter_argument_id", sa.Uuid(), nullable=False),
        sa.Column(
            "outcome",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("recorded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("platform_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('pending', 'won', 'lost')", name="ck_dispute_outcome"
        ),
        sa.ForeignKeyConstraint(
            ["counter_argument_id"],
            ["counter_arguments.id"],
            name=op.f("fk_platform_disputes_counter_argument_id_counter_arguments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
            name=op.f("fk_platform_disputes_recorded_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_disputes")),
        sa.UniqueConstraint("counter_argument_id", name="uq_one_dispute_per_counter"),
    )
    # ### end Alembic commands ###

    # Defence-in-depth (dispute_chain_rule): a rejection may only be created for a
    # task whose status is 'rejected'. Guards against seeders / bulk imports / admin
    # tools that bypass the service layer. The service still enforces this in-app.
    op.execute("""
        CREATE FUNCTION trg_fn_rejection_requires_rejected() RETURNS trigger AS $$
        BEGIN
            IF (SELECT status FROM tasks WHERE id = NEW.task_id) IS DISTINCT FROM 'rejected' THEN
                RAISE EXCEPTION
                    'cannot create a rejection for task %: its status is not rejected',
                    NEW.task_id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """)
    op.execute("""
        CREATE TRIGGER trg_rejection_requires_rejected
            BEFORE INSERT ON rejections
            FOR EACH ROW
            EXECUTE FUNCTION trg_fn_rejection_requires_rejected();
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the trigger + function before the tables they depend on.
    op.execute("DROP TRIGGER IF EXISTS trg_rejection_requires_rejected ON rejections")
    op.execute("DROP FUNCTION IF EXISTS trg_fn_rejection_requires_rejected()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_disputes")
    op.drop_table("counter_arguments")
    op.drop_table("task_attachments")
    op.drop_table("rejections")
    op.drop_table("tasks")
    op.drop_table("availability_logs")
    op.drop_table("rejection_categories")
    # ### end Alembic commands ###
